wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 256
beta1:
  value: 0.8414234168390405
beta2:
  value: 0.9680038847907864
epochs:
  value: 500
hidden_size:
  value:
  - 784
  - 10
learning_rate:
  value: 0.007099906909450224
loss:
  value: mean_squared_error
momentum:
  value: 0.8337275207438168
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0008742440920396431
weight_init:
  value: random
