_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.16
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.16
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": darwin-arm64
activation:
    value:
        - relu
batch_size:
    value: 512
beta:
    value: 0.9
epochs:
    value: 1000
hidden_layers:
    value:
        - 784
input_size:
    value: 784
learning_rate:
    value: 0.1
loss:
    value: cross_entropy
optimizer:
    value: nag
output_size:
    value: 10
weight_decay:
    value: 0.5
weight_init:
    value: random
