wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 1024
beta1:
  value: 0.8680296859634357
beta2:
  value: 0.9859982832029942
epochs:
  value: 300
hidden_size:
  value:
  - 784
learning_rate:
  value: 0.02846849803227419
loss:
  value: cross_entropy
momentum:
  value: 0.8907880608107864
optimizer:
  value: nag
weight_decay:
  value: 6.228959216157914e-05
weight_init:
  value: xavier
