wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 512
beta1:
  value: 0.8093502522202995
beta2:
  value: 0.9579714411453496
epochs:
  value: 300
hidden_size:
  value:
  - 32
  - 64
  - 128
learning_rate:
  value: 0.010092760392358966
loss:
  value: cross_entropy
momentum:
  value: 0.7202026488736262
optimizer:
  value: rmsprop
weight_decay:
  value: 9.15905202699292e-05
weight_init:
  value: xavier
