wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 1024
beta1:
  value: 0.9106759017606998
beta2:
  value: 0.99124038883007
epochs:
  value: 800
hidden_size:
  value:
  - 128
  - 256
learning_rate:
  value: 0.010339037816844652
loss:
  value: cross_entropy
momentum:
  value: 0.5064521083623105
optimizer:
  value: rmsprop
weight_decay:
  value: 5.539299712330581e-06
weight_init:
  value: xavier
