wandb_version: 1

activation:
  value: relu
batch_size:
  value: 512
beta1:
  value: 0.8386853908252628
beta2:
  value: 0.984185790875538
epochs:
  value: 300
hidden_size:
  value:
  - 784
learning_rate:
  value: 0.00116384667621447
loss:
  value: cross_entropy
momentum:
  value: 0.8971301542633365
optimizer:
  value: momentum
weight_decay:
  value: 0.0001145853898934256
weight_init:
  value: random
