wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 1024
beta1:
  value: 0.915859068868367
beta2:
  value: 0.9982903497666142
epochs:
  value: 300
hidden_size:
  value:
  - 784
learning_rate:
  value: 0.09733534770199888
loss:
  value: cross_entropy
momentum:
  value: 0.6623217820776233
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0008803700339637965
weight_init:
  value: xavier
