wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 1024
beta1:
  value: 0.8769372083154475
beta2:
  value: 0.9410056918691436
epochs:
  value: 300
hidden_size:
  value:
  - 784
learning_rate:
  value: 0.02949359039287619
loss:
  value: cross_entropy
momentum:
  value: 0.9183891051734576
optimizer:
  value: rmsprop
weight_decay:
  value: 9.043359212775637e-05
weight_init:
  value: xavier
