_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.16
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.8.16
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": darwin-arm64
        visualize:
            Confusion matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Confusion matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
activation:
    value: tanh
batch_size:
    value: 2048
beta:
    value: 0.5
beta1:
    value: 0.9039839560725784
beta2:
    value: 0.9345220815205774
dataset:
    value: fashion_mnist
epochs:
    value: 1000
epsilon:
    value: 1e-06
hidden_size:
    value:
        - 128
        - 256
input_size:
    value: 784
learning_rate:
    value: 0.02333126481135045
loss:
    value: cross_entropy
momentum:
    value: 0.6133638614591184
num_layers:
    value: 1
optimizer:
    value: sgd
output_size:
    value: 10
sweep_id:
    value: null
wandb_entity:
    value: da24d008-iit-madras
wandb_project:
    value: da24d008-assignment1
wandb_sweep:
    value: true
weight_decay:
    value: 0.0004861956778111493
weight_init:
    value: random
