_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.16
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.8.16
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": darwin-arm64
activation:
    value: identity
batch_size:
    value: 512
beta:
    value: 0.5
beta1:
    value: 0.8016383631247513
beta2:
    value: 0.924843658677814
dataset:
    value: fashion_mnist
epochs:
    value: 500
epsilon:
    value: 1e-06
hidden_size:
    value:
        - 784
        - 32
input_size:
    value: 784
learning_rate:
    value: 0.012993343242896754
loss:
    value: mean_squared_error
momentum:
    value: 0.5990460727841174
num_layers:
    value: 1
optimizer:
    value: momentum
output_size:
    value: 10
sweep_id:
    value: da24d008-iit-madras/da24d008-assignment1/dikagoze
wandb_entity:
    value: da24d008-iit-madras
wandb_project:
    value: da24d008-assignment1
wandb_sweep:
    value: true
weight_decay:
    value: 0.0008651111553590617
weight_init:
    value: xavier
