wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 830
beta:
  value: 1.4098707134847122
beta1:
  value: 0.3895106855460423
beta2:
  value: 1.8621383437810175
epochs:
  value: 595
epsilon:
  value: 1.611159095046067e-06
input_size:
  value: 809
learning_rate:
  value: 0.006811220931850607
loss:
  value: cross_entropy
loss_function:
  value: cross entropy
momentum:
  value: 0.7396842027537356
num_layers:
  value: 4
optimizer:
  value: adam
output_size:
  value: 14
wandb_entity:
  value: da24d008-iit-madras
wandb_project:
  value: da24d008-assignment1
wandb_sweep:
  value: 'false'
weight_decay:
  value: 0.3035204884641105
weight_init:
  value: xavier
