wandb_version: 1

activation:
  value: relu
batch_size:
  value: 801
beta:
  value: 0.4704397418101676
beta1:
  value: 0.3157994316579099
beta2:
  value: 0.4395198648753939
epochs:
  value: 834
epsilon:
  value: 1.0908586563889285e-06
input_size:
  value: 1374
learning_rate:
  value: 0.10310739402676591
loss:
  value: cross_entropy
loss_function:
  value: cross entropy
momentum:
  value: 0.8694381122494576
num_layers:
  value: 1
optimizer:
  value: nag
output_size:
  value: 16
wandb_entity:
  value: da24d008-iit-madras
wandb_project:
  value: da24d008-assignment1
wandb_sweep:
  value: 'true'
weight_decay:
  value: 0.8461480254665359
weight_init:
  value: xavier
