_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.16
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.8.16
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": darwin-arm64
        visualize:
            Confusion matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Confusion matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
activation:
    value: sigmoid
batch_size:
    value: 256
beta:
    value: 0.5
beta1:
    value: 0.8206565020187984
beta2:
    value: 0.9658669501402743
dataset:
    value: fashion_mnist
epochs:
    value: 500
epsilon:
    value: 1e-06
hidden_size:
    value:
        - 784
input_size:
    value: 784
learning_rate:
    value: 0.00191676387271678
loss:
    value: mean_squared_error
momentum:
    value: 0.8701147625530561
num_layers:
    value: 1
optimizer:
    value: rmsprop
output_size:
    value: 10
sweep_id:
    value: da24d008-iit-madras/da24d008-assignment1/dikagoze
sweep_name:
    value: epochs-500_batch_size-256_loss-mean_squared_error_optimizer-rmsprop_learning_rate-0.00191676387271678_weight_init-random_hidden_size-[784]_num_layers-1_beta-0.5_activation-sigmoid_weight_decay-0.0002466490302743326_beta1-0.8206565020187984_beta2-0.9658669501402743_epsilon-1e-06_momentum-0.8701147625530561
wandb_entity:
    value: da24d008-iit-madras
wandb_project:
    value: da24d008-assignment1
wandb_sweep:
    value: true
weight_decay:
    value: 0.0002466490302743326
weight_init:
    value: random
