wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 512
beta1:
  value: 0.8172686923165681
beta2:
  value: 0.9030720618097694
epochs:
  value: 500
hidden_size:
  value:
  - 1024
  - 512
  - 256
learning_rate:
  value: 0.000912412399576164
loss:
  value: cross_entropy
momentum:
  value: 0.5206474691255172
num_layers:
  value: 2
optimizer:
  value: adam
weight_decay:
  value: 0.0008880382754057763
weight_init:
  value: xavier
