wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 256
beta1:
  value: 0.9245126782639332
beta2:
  value: 0.9683398072845288
epochs:
  value: 500
hidden_size:
  value:
  - 784
learning_rate:
  value: 0.03392699971770147
loss:
  value: mean_squared_error
momentum:
  value: 0.5557095138626539
optimizer:
  value: momentum
weight_decay:
  value: 0.0004884425222140604
weight_init:
  value: random
