_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.16
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.8.16
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": darwin-arm64
activation:
    value: tanh
batch_size:
    value: 512
beta:
    value: 0.5
beta1:
    value: 0.9166056836814666
beta2:
    value: 0.964610163340107
dataset:
    value: fashion_mnist
epochs:
    value: 800
epsilon:
    value: 1e-06
hidden_size:
    value:
        - 784
        - 32
input_size:
    value: 784
learning_rate:
    value: 0.07336410654488294
loss:
    value: mean_squared_error
momentum:
    value: 0.943000374815917
num_layers:
    value: 1
optimizer:
    value: sgd
output_size:
    value: 10
sweep_id:
    value: null
wandb_entity:
    value: da24d008-iit-madras
wandb_project:
    value: da24d008-assignment1
wandb_sweep:
    value: true
weight_decay:
    value: 0.00015643257183003956
weight_init:
    value: random
