_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.16
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.8.16
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": darwin-arm64
activation:
    value: relu
batch_size:
    value: 512
beta:
    value: 0.5
beta1:
    value: 0.8830025862455038
beta2:
    value: 0.9746961255862764
epochs:
    value: 1000
epsilon:
    value: 1e-06
hidden_size:
    value:
        - 512
        - 256
input_size:
    value: 784
learning_rate:
    value: 0.0037460457340916776
loss:
    value: cross_entropy
momentum:
    value: 0.5139366029661006
num_layers:
    value: 1
optimizer:
    value: rmsprop
output_size:
    value: 10
wandb_entity:
    value: da24d008-iit-madras
wandb_project:
    value: da24d008-assignment1
wandb_sweep:
    value: true
weight_decay:
    value: 0.0007730509640274825
weight_init:
    value: xavier
