_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.16
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.8.16
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": darwin-arm64
        visualize:
            Confusion matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Confusion matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
activation:
    value: tanh
batch_size:
    value: 256
beta:
    value: 0.5
beta1:
    value: 0.809692840276903
beta2:
    value: 0.9701418608685982
dataset:
    value: fashion_mnist
epochs:
    value: 500
epsilon:
    value: 1e-06
hidden_size:
    value:
        - 32
        - 64
        - 128
input_size:
    value: 784
learning_rate:
    value: 0.010349089939840857
loss:
    value: cross_entropy
momentum:
    value: 0.8768012006320032
num_layers:
    value: 1
optimizer:
    value: rmsprop
output_size:
    value: 10
sweep_id:
    value: da24d008-iit-madras/da24d008-assignment1/dikagoze
sweep_name:
    value: epochs-500_batch_size-256_loss-cross_entropy_optimizer-rmsprop_learning_rate-0.010349089939840857_weight_init-xavier_hidden_size-[32, 64, 128]_num_layers-1_beta-0.5_activation-tanh_weight_decay-3.9772540717127104e-05_beta1-0.809692840276903_beta2-0.9701418608685982_epsilon-1e-06_momentum-0.8768012006320032
wandb_entity:
    value: da24d008-iit-madras
wandb_project:
    value: da24d008-assignment1
wandb_sweep:
    value: true
weight_decay:
    value: 3.9772540717127104e-05
weight_init:
    value: xavier
