_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.16
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 13
                - 14
                - 16
                - 23
                - 55
            "4": 3.8.16
            "5": 0.19.8
            "8":
                - 2
                - 5
            "12": 0.19.8
            "13": darwin-arm64
        visualize:
            Confusion matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Confusion matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
activation:
    value: sigmoid
batch_size:
    value: 256
beta:
    value: 0.5
beta1:
    value: 0.8869744121245234
beta2:
    value: 0.9222763401894836
epochs:
    value: 1000
epsilon:
    value: 1e-06
hidden_size:
    value:
        - 512
input_size:
    value: 784
learning_rate:
    value: 0.00017946968176270217
loss:
    value: cross_entropy
momentum:
    value: 0.8974459300445876
num_layers:
    value: 1
optimizer:
    value: rmsprop
output_size:
    value: 10
sweep_name:
    value: epochs-1000_batch_size-256_loss-cross_entropy_optimizer-rmsprop_learning_rate-0.00017946968176270217_weight_init-random_hidden_size-[512]_num_layers-1_beta-0.5_activation-sigmoid_weight_decay-5.139020503053859e-05_beta1-0.8869744121245234_beta2-0.9222763401894836_epsilon-1e-06_momentum-0.8974459300445876_wandb_sweep-True
wandb_entity:
    value: da24d008-iit-madras
wandb_project:
    value: da24d008-assignment1
wandb_sweep:
    value: true
weight_decay:
    value: 5.139020503053859e-05
weight_init:
    value: random
